services:
  buddyscript-api:
    container_name: buddyscript-api
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env
    networks:
      - buddynet

networks:
  buddynet:
    external: true
